### ISSUE TITLE
[Bug] ShowHiddenChannels: hidden channels show up annoyingly in the inbox

### ISSUE THREAD

**Issue by ilyamikheevcoder** [Vendicated/Vencord#618]
### Discord Account

ilya.mikheev.coder#9359

### What happens when the bug or crash occurs?

Hidden channels are clogging up my inbox!
![изображение](https://user-images.githubusercontent.com/37904672/226386781-d6a611d6-433d-41e1-bdcf-7c6196a57f82.png)

### What is the expected behaviour?

Hidden channels should not appear in the inbox.

### How do you recreate this bug or crash?

1. Enable ShowHiddenChannels
2. Open your inbox

### Errors

```
Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
    at 4b9659d7526aa3979710.js:103
    at async Promise.all (index 3)
```
that is probably not relevant

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
known issue, introduced in https://github.com/Vendicated/Vencord/commit/e36f4e5b0aed93f6b24a42eb738fc5f38579bf3c
